name: Integration tests

on:
  # Use the following to explicitly start this workflow.
  # packages/deployment/scripts/start-github-integration-test.sh <BRANCH-OR-TAG>
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
      run_id:
        required: false
        type: string
  push:
    branches: ['build-release-*']

concurrency:
  group: ${{ github.workflow }}-${{ inputs.run_id || github.ref }}
  cancel-in-progress: ${{ inputs.run_id == '' }}

jobs:
  # This job is meant to emulate what developers working with the Agoric platform will experience
  # It should be kept in sync with https://agoric.com/documentation/getting-started/
  getting-started:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cli: [link-cli/yarn, registry/yarn, registry/npm, registry/npx]
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Reconfigure git to use HTTP authentication
        run: git config --global url."https://github.com/".insteadOf ssh://git@github.com/
        shell: bash

      # Prerequisites
      - uses: ./.github/actions/restore-node
        with:
          node-version: 18.18
          keep-endo: 'true'

      # Select a branch on dapp to test against by adding text to the body of the
      # pull request. For example: #getting-started-branch: zoe-release-0.7.0
      # The default is 'main'
      - name: Get the appropriate dapp branch
        id: get-branch
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            let branch = 'main';
            if (context.payload.pull_request) {
              const { body } = context.payload.pull_request;
              const regex = /^\#getting-started-branch:\s+(\S+)/m;
              const result = regex.exec(body);
              if (result) {
                branch = result[1];
              }
            }
            console.log('getting-started dapp branch: ' + branch);
            return branch;

      - name: Start local NPM registry
        if: ${{ startsWith(matrix.cli, 'registry') }}
        run: |
          set -xe
          git reset --hard HEAD
          git clean -f
          git config user.email "noreply@agoric.com"
          REGISTRY_PUBLISH_WORKSPACES="$HOME/endo"
          timeout 900 scripts/registry.sh bg-publish ${{ matrix.cli }}

      - name: run agoric-cli integration-test
        # These integration tests can be flaky so retry automatically
        uses: nick-fields/retry@v3
        with:
          # This step usually takes <4 minutes (after 6m setup). The
          # deployment-test running in parallel takes 35 minutes so 20 minutes
          # won't increase the time for this workflow to complete.
          timeout_minutes: 20
          command: scripts/registry.sh test ${{ matrix.cli }} ${{steps.get-branch.outputs.result}}
          on_retry_command: rm -f $HOME/bin/agoric

      - name: notify on failure
        if: >
          false && failure() && github.event_name != 'pull_request' &&
          github.repository_owner == 'agoric'
        uses: ./.github/actions/notify-status
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          from: ${{ secrets.NOTIFY_EMAIL_FROM }}
          to: ${{ secrets.NOTIFY_EMAIL_TO }}
          password: ${{ secrets.NOTIFY_EMAIL_PASSWORD }}
