name: Remote Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message from the remote repo'
        required: true
        default: 'Hello from remote'
      data:
        description: 'Additional data'
        required: false

jobs:
  run-remote-triggered-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run triggered action
        run: |
          echo "Workflow triggered remotely!"
          echo "Message: ${{ github.event.inputs.message }}"
          echo "Additional data: ${{ github.event.inputs.data }}"
